# fly.toml app configuration file generated for activitynetwork on 2024-01-02T19:39:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "activitynetwork"
primary_region = "ams"

[build]
  image = "petrk12/activitynetwork:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dpw7oikn6"
  Cloudinary__ApiKey="249931556247775"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
